#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ai-test-project - AI Project
Test AI projesi - otomatik oluşturuldu

Auto-generated by AI Master System
"""

import os
import logging
from transformers import pipeline
from flask import Flask, request, jsonify

# Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class Ai_Test_ProjectAI:
    def __init__(self):
        logger.info("🤖 ai-test-project AI başlatılıyor...")
        self.model = None
        self.load_model()
    
    def load_model(self):
        """AI modelini yükle"""
        try:
            self.model = pipeline("text-generation", model="microsoft/DialoGPT-medium")
            logger.info("✅ Model yüklendi")
        except Exception as e:
            logger.error(f"❌ Model yükleme hatası: {e}")
    
    def process(self, input_text: str) -> str:
        """Metni işle"""
        if not self.model:
            return "Model yüklenmedi"
        
        try:
            result = self.model(input_text, max_length=100)
            return result[0]['generated_text']
        except Exception as e:
            return f"Hata: {e}"

# Flask API
app = Flask(__name__)
ai_system = Ai_Test_ProjectAI()

@app.route('/api/process', methods=['POST'])
def api_process():
    data = request.json
    text = data.get('text', '')
    result = ai_system.process(text)
    return jsonify({'result': result})

@app.route('/')
def index():
    return f"""
    <h1>ai-test-project</h1>
    <p>Test AI projesi - otomatik oluşturuldu</p>
    <p>API Endpoint: /api/process</p>
    """

if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0', port=5000)
